backend/server/src/main/java/com/issuetracker/intercepter/LoginInterceptor.java
=> [BE] Authorization 이 없을 경우에 대한 버그 픽스

backend/README.md, backend/docker/db/initdb/1_schema.sql, backend/docker/docker-compose.yml
로컬 환경에서 6379 포트가 사용중 이어서 포트를 변경했습니다.
=> feat: redis 6379 포트를 15552 포트로 변경

backend/docker/db/initdb/1_schema.sql, backend/server/src/main/java/com/issuetracker/domain/auth/User.java, backend/server/src/main/java/com/issuetracker/dto/auth/UserDto.java, backend/server/src/main/java/com/issuetracker/repository/UserRepository.java, backend/server/src/main/java/com/issuetracker/util/JwtUtil.java, backend/server/src/main/resources/static/index.html
토큰에 프로필 이미지 경로를 추가했습니다.
login 필드는 추후 이메일 필드가 추가되면 제거하겠습니다.
=> feat: JWT claim에 profileImageUrl 추가

backend/docker/db/initdb/1_schema.sql, backend/server/build.gradle, backend/server/src/main/java/com/issuetracker/controller/AuthController.java, backend/server/src/main/java/com/issuetracker/controller/ios/IosAuthController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebAuthController.java, backend/server/src/main/java/com/issuetracker/domain/auth/Auth.java, backend/server/src/main/java/com/issuetracker/domain/auth/User.java, backend/server/src/main/java/com/issuetracker/dto/auth/UserDto.java, backend/server/src/main/java/com/issuetracker/dto/auth/UserEmailDto.java, backend/server/src/main/java/com/issuetracker/dto/auth/UserInfoDto.java, backend/server/src/main/java/com/issuetracker/intercepter/LoginInterceptor.java, backend/server/src/main/java/com/issuetracker/repository/UserRepository.java, backend/server/src/main/java/com/issuetracker/service/AuthService.java, backend/server/src/main/java/com/issuetracker/service/UserService.java, backend/server/src/main/java/com/issuetracker/service/github/GitHubService.java, backend/server/src/main/java/com/issuetracker/util/JwtUtil.java, backend/server/src/main/resources/static/index.html
- 이메일 정보를 포함한 유저 정보가 jwt로 잘 생성됩니다.
- 현재 authService.authenticate 가 정상적으로 되지 않는 문제점이 있습니다.
=> [BE] Github의 OAuth 로그인시 이메일 정보 저장

backend/docker/db/initdb/1_schema.sql, backend/docker/db/initdb/2_data.sql
Insert 문을 제외하고, 테이블을 생성하는 쿼리를 우선적으로 작성했습니다.
혹시나 몰라서 외래키 제약 조건에 일일히 네이밍을 하였는데,
굳이 네이밍을 할 필요가 없으려나요?
의견 구합니다.
=> [BE] DB 테이블의 CREATE 쿼리 초안 작성

backend/server/build.gradle, backend/server/src/main/java/com/issuetracker/service/github/GitHubService.java
webflux 를 제거해서 restTemplate 으로 통일했습니다.
월요일날 회의 때, 다른 분들께도 잘 동작한다고 확인받으면, 머지하겠습니다.
#63  이 먼저 머지되어야 합니다.
=> [BE] webflux 제거

frontend/issue-cracker/src/App.tsx, frontend/issue-cracker/src/components/common/IssueHeaderButton.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneAdd/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneEdit/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneNav/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneCell.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneTableHeader.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/index.tsx, frontend/issue-cracker/src/utils/const.ts
=> feat: Milestone Layout

frontend/issue-cracker/src/App.tsx, frontend/issue-cracker/src/components/common/SideBar.tsx, frontend/issue-cracker/src/components/common/SideBarDrop.tsx, frontend/issue-cracker/src/components/common/group/TabGroup.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueNav/index.tsx, frontend/issue-cracker/src/store/Recoil.tsx, frontend/issue-cracker/src/utils/const.ts
-ghojeong/issue-tracker/#72
Milestone branch (#73 ) 와 병합
=> feat: SideBar 클릭 시 SideBarDrop 등장, 모달 외 영역 클릭 시 닫힘

backend/docker/db/initdb/1_schema.sql, backend/docker/db/initdb/2_data.sql
=> [BE] 이슈트래커 기본 INSERT 쿼리문

backend/README.md, backend/deploy.sh
제가 Spring 서버를 어떻게 배포했는지에 관한 간단한 스크립트 파일과, 안내 문서를 작성했습니다.
=> [BE] 배포 스크립트 및 안내를 문서화

backend/server/build.gradle, backend/server/src/main/java/com/issuetracker/domain/Milestones.java, backend/server/src/main/java/com/issuetracker/dto/ios/IosAssigneesDto.java, backend/server/src/main/java/com/issuetracker/dto/web/WebAssigneesDto.java, backend/server/src/main/java/com/issuetracker/repository/CommentRepository.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/LabelRepository.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/repository/mapper/LabelMapper.java, backend/server/src/main/java/com/issuetracker/repository/sql/AssigneeQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/CommentQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/LabelQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/MilestoneQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/UserQueries.kt, backend/server/src/main/java/com/issuetracker/service/ios/IosMilestoneService.java, backend/server/src/main/java/com/issuetracker/service/web/WebMilestoneService.java
우선 구현을 생각하고 작성해서, 코드 정리는 PR을 올리고 차차 진행하겠습니다!
궁금한 점. 
1. IssueRepository에서 Assignee이나 Label 등의 정보를 가져와도 되는지?
2. IssueRepository에서 이슈 옵션(담당자, 레이블, 마일스톤) 리스트를 줄 때 이슈 정보와 마일스톤ID는 필요 없어서 아래와 같이 초기화 했는데 괜찮을까요? `new Issues(new ArrayList<>()`
```java
//TODO. 마일스톤 id,와 issue를 또 한번 마일스톤을 돌아서 구할지?
long cnt = 0L;
Milestones milestones = new Milestones(new ArrayList<>());
for (MilestoneInfo milestoneInfo : milestoneInfoList) {
milestones.add(new Milestone(++cnt, new Issues(new ArrayList<>()), milestoneInfo));
}
```
```json
{
"labels": [
{
"id": 1,
"title": "라벨1 제목",
"description": "라벨1 설명",
"background_color_hexa": "#FFFFF",
"text_color_hexa": "#FFFFF"
},
{
"id": 2,
"title": "라벨2 제목",
"description": "라벨2 설명",
"background_color_hexa": "#FFFFF",
"text_color_hexa": "#FFFFF"
}
],
"assignees": [
{
"id": …
```
=> feat: IssueOptionList, MilestoneList API 구현

backend/docker/db/initdb/2_data.sql, backend/server/src/main/java/com/issuetracker/controller/ios/IosIssueController.java, backend/server/src/main/java/com/issuetracker/controller/ios/IosLabelController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebLabelController.java, backend/server/src/main/java/com/issuetracker/domain/NewIssue.java, backend/server/src/main/java/com/issuetracker/dto/ios/IosIssueDetailDto.java, backend/server/src/main/java/com/issuetracker/dto/ios/IosNewIssueDto.java, backend/server/src/main/java/com/issuetracker/dto/web/WebAssigneesDto.java, backend/server/src/main/java/com/issuetracker/dto/web/WebIssueDetailDto.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt, backend/server/src/main/java/com/issuetracker/service/ios/IosIssueService.java, backend/server/src/main/java/com/issuetracker/service/ios/IosLabelService.java, backend/server/src/main/java/com/issuetracker/service/web/WebIssueService.java, backend/server/src/main/java/com/issuetracker/service/web/WebLabelService.java
=> 이슈 생성, 레이블 리스트 API 구현

backend/deploy.sh, backend/revive.sh
변경사항이 대단치 않으므로, 셀프머지 하도록 하겠습니다.
=> [BE] 서버가 죽었을시 재실행하는 스크립트 작성

backend/docker/db/initdb/1_schema.sql, backend/docker/db/initdb/2_data.sql, backend/server/src/main/java/com/issuetracker/controller/AuthController.java, backend/server/src/main/java/com/issuetracker/controller/ios/IosAuthController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebAuthController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebLabelController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebMilestoneController.java, backend/server/src/main/java/com/issuetracker/domain/Assignee.java, backend/server/src/main/java/com/issuetracker/domain/Label.java, backend/server/src/main/java/com/issuetracker/domain/Writer.java, backend/server/src/main/java/com/issuetracker/domain/auth/User.java, backend/server/src/main/java/com/issuetracker/dto/auth/AuthResponse.java, backend/server/src/main/java/com/issuetracker/dto/auth/UserDto.java, backend/server/src/main/java/com/issuetracker/dto/request/NewLabelRequest.java, backend/server/src/main/java/com/issuetracker/dto/response/AssigneeResponse.java, backend/server/src/main/java/com/issuetracker/dto/response/UserResponse.java, backend/server/src/main/java/com/issuetracker/dto/response/WriterResponse.java, backend/server/src/main/java/com/issuetracker/repository/CommentRepository.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/LabelRepository.java, backend/server/src/main/java/com/issuetracker/repository/UserRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/AssigneeQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/CommentQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/LabelQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/UserQueries.kt, backend/server/src/main/java/com/issuetracker/service/LabelService.java, backend/server/src/main/java/com/issuetracker/util/JwtUtil.java
라벨을 추가하는 API 를 구현했습니다.
하는 김에 거슬려서 profileImageUrl 을 avatarUrl 로 통일했습니다.
=> [BE] 라벨 추가 API 구현

backend/server/src/main/java/com/issuetracker/controller/web/WebMilestoneController.java, backend/server/src/main/java/com/issuetracker/dto/request/NewMilestoneRequest.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/MilestoneQueries.kt, backend/server/src/main/java/com/issuetracker/service/MilestoneService.java
=> [BE] 마일스톤 추가 API 구현

backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/dto/request/NewCommentRequest.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt, backend/server/src/main/java/com/issuetracker/service/IssueService.java
=> [BE] Comment 추가 API 구현

backend/server/src/main/java/com/issuetracker/controller/ios/IosIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebLabelController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebMilestoneController.java, backend/server/src/main/java/com/issuetracker/dto/request/CommentRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/IssueRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/LabelRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/MilestoneRequest.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/LabelRepository.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/CommentQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/LabelQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/MilestoneQueries.kt, backend/server/src/main/java/com/issuetracker/service/IssueService.java, backend/server/src/main/java/com/issuetracker/service/LabelService.java, backend/server/src/main/java/com/issuetracker/service/MilestoneService.java
Label, Milestone, Comment 의 수정 API 를 구현했습니다.
=> [BE] 수정 API 구현

frontend/issue-cracker/src/components/common/sideBar/content/LabelContent.tsx, frontend/issue-cracker/src/components/layout/Header/index.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueTable/IssueCell.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelAdd/InputColorBox.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelAdd/InputContentBox.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelAdd/LabelBox.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelAdd/index.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelTable/LabelCell.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelTable/index.tsx, frontend/issue-cracker/src/components/layout/LabelList/index.tsx, frontend/issue-cracker/src/store/Recoil.tsx, frontend/issue-cracker/src/utils/types/sideBarType.ts
- Label 제목
- Label 내용
- Label  배경 색상
- Label 글자 색상
LabelAdd  component  복잡해서 3가지로 분리
=> [FE] LabelAdd  생성과 색상변경

frontend/issue-cracker/src/components/common/IssueHeaderButton.tsx, frontend/issue-cracker/src/components/layout/Header/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneAdd/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneCell.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneTableHeader.tsx, frontend/issue-cracker/src/components/layout/Milestone/index.tsx, frontend/issue-cracker/src/store/Recoil.tsx, frontend/issue-cracker/src/utils/types/milestoneDataType.ts, frontend/issue-cracker/src/utils/util.ts
- Milestone 관련 util 함수 수정
- Milestone POST api 수정 적용
=> [FE] Milestone 생성과 편집

backend/docker/db/initdb/1_schema.sql, backend/server/src/main/java/com/issuetracker/dto/request/MilestoneRequest.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/MilestoneQueries.kt
마일스톤 추가시 dueDate 를 입력받을 수 있도록 하면서,
기존의 findAllMilestoneInfo 을 수정했습니다.
=> [BE] 마일스톤 추가시, dueDate 를 입력받도록 기능 확장

backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java
dueDate 가 null 일 경우에 대한 핸들링이 되어있지 않아서 발생한 에러였습니다.
=> [BE] 이슈 옵션 조회 API 에러 해결

backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/CommentQueries.kt, backend/server/src/main/java/com/issuetracker/service/IssueService.java
> `DELETE`  api/web/issues/{이슈번호}/comments/{댓글번호}
- 본인이 작성한 댓글만 제거할 수 있습니다.
```json
{
"message": "타인의 댓글은 제거할 수 없습니다."
}
```
=> feat: Comment 삭제 API

backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/domain/UpdateIssue.java, backend/server/src/main/java/com/issuetracker/dto/request/UpdateIssueMilestoneRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/UpdateIssueRequest.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt, backend/server/src/main/java/com/issuetracker/service/IssueService.java
milestoneId 를 별도의 API 에서 수정할 수 있도록 분리했습니다.
확인해보시고, 정상작동하면 머지 후 문서 업데이트까지 부탁드립니다.
=> [BE] Issue 수정에서 마일스톤을 수정하는 부분을 별도의 API 로 분리

frontend/issue-cracker/src/components/common/CommonButton.tsx, frontend/issue-cracker/src/components/common/IssueHeaderButton.tsx, frontend/issue-cracker/src/components/common/group/TabGroup.tsx, frontend/issue-cracker/src/components/common/sideBar/SideBarDropAssignee.tsx, frontend/issue-cracker/src/components/common/sideBar/SideBarDropLabel.tsx, frontend/issue-cracker/src/components/layout/IssueAdd/IssueAddButton.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueTable/IssueCell.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueTable/IssueTableHeader.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueTable/index.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelTable/LabelCell.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelTable/LabelDeleteButton.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelTable/LabelEditButton.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelTable/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneAdd/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneNav/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneCell.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneCloseButton.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneDeleteButton.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneEditButton.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneTableHeader.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/index.tsx, frontend/issue-cracker/src/store/Recoil.tsx, frontend/issue-cracker/src/utils/const.ts, frontend/issue-cracker/src/utils/restAPI.ts, frontend/issue-cracker/src/utils/types/commonTypes.ts, frontend/issue-cracker/src/utils/useFetch.ts, frontend/issue-cracker/src/utils/util.ts
- Recoil 비동기 로직 삭제
- useFetch Custom Hook 생성 및 적용
- 레이블 & 마일스톤 api 호출 및 데이터 적용
- CommonButton 컴포넌트 네이밍 변경 및 파일 분리
=> [FE] 레이블 및 마일스톤 api 호출 작업

backend/server/src/main/java/com/issuetracker/controller/web/WebAssigneeController.java, backend/server/src/main/java/com/issuetracker/dto/response/AssigneesResponse.java, backend/server/src/main/java/com/issuetracker/repository/AssigneeRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/AssigneeQueries.kt, backend/server/src/main/java/com/issuetracker/service/AssigneeService.java
구현을 하면서 파이로가 만드신 ResponseMapper 를 확인했는데,
Mapper를 만드는 기준??이 궁금해서 질문 드리게 됐습니다.
혹시 ResponseMapper의 역할이 DTO List를 생성하는 거 외에 다른 용도로도 사용이 될 수 있나요?
=> [BE] Assignees 목록 반환하는 GET API 작성

backend/server/build.gradle, backend/server/src/main/java/com/issuetracker/controller/ExceptionController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/dto/request/InsertIssueRequest.java, backend/server/src/main/java/com/issuetracker/dto/response/MessagesResponse.java, backend/server/src/main/java/com/issuetracker/intercepter/LoginInterceptor.java
무작정 그냥 500 에러만 나던 것을 프론트분들이 디버깅하기 쉽도록,
다양한 상황에서의 에러메시지를 좀더 상세하게 안내할 수 있도록 하였습니다.
=> [BE] 이슈 생성시의 예외처리 강화

backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/util/TimestampUtil.java
Null 로 인한 500 에러를 해결했습니다.
애초에 시간을 반환하는 타입을 Timestamp 가 아니라,
LocalDateTime으로 한 이유가 궁금해서 여쭈어봅니다.
그냥 Timestamp 로 했으면, 지금과 같은 null 체크로 고생하지 않았을 것 같아서요.
Timestamp 의 파싱은 프론트분들에게 맡겨도 되었던것 아닌가요?
=> [BE] toLocalDateTime 을 할 때의 null 로 인한 에러 해결

frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/IssueDetailComment.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/IssueDetailDisplay.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/index.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailTitle.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/index.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueTable/IssueCell.tsx, frontend/issue-cracker/src/store/Recoil.tsx, frontend/issue-cracker/src/utils/types/commonTypes.ts
- useFetch로 IssueDetail data 받아오지만 null로 인한 destructuring 문제 발생 -> ?로해결
- ghojeong/issue-tracker/#173
=> [FE] IssueDetail Data useFetch 방식으로 변경

backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebLabelController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebMilestoneController.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/LabelRepository.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/service/IssueService.java, backend/server/src/main/java/com/issuetracker/service/LabelService.java, backend/server/src/main/java/com/issuetracker/service/MilestoneService.java
https://github.com/ghojeong/issue-tracker/issues/165
=> feat: 생성 API의 리턴 값으로 PK 를 보내기

backend/docker/db/initdb/2_data.sql, backend/server/src/main/java/com/issuetracker/repository/AssigneeRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/AssigneeQueries.kt
https://github.com/ghojeong/issue-tracker/issues/174
=> fix: 로그인한 유저가 담당자 리스트에 출력되지 않는 문제

backend/docker/Dockerfile.pyrodb
=> [BE] MySQL 의 timezone 을 한국 시간대로 변경

backend/docker/db/initdb/2_data.sql, backend/server/src/main/java/com/issuetracker/repository/AssigneeRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/AssigneeQueries.kt
Reverts ghojeong/issue-tracker#176
=> Revert "fix: 로그인한 유저가 담당자 리스트에 출력되지 않는 문제"

backend/docker/db/initdb/2_data.sql, backend/server/src/main/java/com/issuetracker/repository/AssigneeRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/AssigneeQueries.kt
Reverts ghojeong/issue-tracker#187
=> Revert "Revert "fix: 로그인한 유저가 담당자 리스트에 출력되지 않는 문제""

backend/server/src/main/java/com/issuetracker/controller/web/WebAuthController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebLabelController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebMilestoneController.java, backend/server/src/main/java/com/issuetracker/dto/auth/AuthRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/CommentRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/InsertIssueRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/LabelRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/MilestoneRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/UpdateIssueMilestoneRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/UpdateIssueRequest.java
- Validation을 하면서 궁금했던 점은 URL의 @PathVariable 로 들어오는 값도 유효성 검사를 해야 하지 않을까? 였는데
- 
```java
@GetMapping("/{issueId}/comments")
public CommentsResponse commentList(@PathVariable Long issueId) {
return issueService.findCommentsByIssueId(issueId);
}
```
[How to validate Spring MVC @PathVariable values?](https://stackoverflow.com/questions/19419234/how-to-validate-spring-mvc-pathvariable-values)를 보고 이해한 바는 아래와 같습니다.
1. @PathVariable은 원칙적으로 유효 해야한다.
2. @PathVariable이 잘못된 경우
2.1 버그로 인해 잘못된 URL이 생성된 경우
2.2 사용자가 URL을 조작하고 있는 경우이기 때문에, 
에러 처리를 해줄 필요가 없다 입니다.. 제가 이해한 내용이 맞는지 확인 해주시면 감사하겠습니다..😥
=> feat: Validation 검사 적용(#157)

backend/server/src/main/java/com/issuetracker/controller/ios/IosIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java, backend/server/src/main/java/com/issuetracker/controller/web/WebMilestoneController.java, backend/server/src/main/java/com/issuetracker/dto/request/IssuesNumbersRequest.java, backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java, backend/server/src/main/java/com/issuetracker/repository/MilestoneRepository.java, backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt, backend/server/src/main/java/com/issuetracker/repository/sql/MilestoneQueries.kt, backend/server/src/main/java/com/issuetracker/service/IssueService.java, backend/server/src/main/java/com/issuetracker/service/MilestoneService.java
현재 URL 설계가 뭔가 이상하다는 생각이 듭니다..
CLOSE, OPEN 동사를 쓰는 게 맞는지..잘 모르겠습니다..
=> feat: 이슈 닫기/열기 API 구현

backend/server/src/main/java/com/issuetracker/controller/web/WebAuthController.java, backend/server/src/main/java/com/issuetracker/service/github/GitHubLocalhostService.java
이슈크래커 추가 개발하기 위해 하나 더 만든 Github OAuth App 를 위한 API 를 추가함
=> [BE] localhost 를 위한 OAuth 로그인 API 를 추가

backend/server/src/main/java/com/issuetracker/dto/auth/AuthRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/AssigneesRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/CommentRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/InsertIssueRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/IssuesNumbersRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/LabelNumbersRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/LabelRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/MilestoneRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/UpdateIssueMilestoneRequest.java, backend/server/src/main/java/com/issuetracker/dto/request/UpdateIssueRequest.java, frontend/issue-cracker/src/components/common/TextArea.tsx, frontend/issue-cracker/src/components/common/group/ButtonGroup.tsx, frontend/issue-cracker/src/components/layout/IssueAdd/IssueAddButton.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueNav/index.tsx, frontend/issue-cracker/src/components/layout/IssueList/IssueTable/IssueTableHeader.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelAdd/index.tsx, frontend/issue-cracker/src/components/layout/LabelList/LabelEdit/LabelEditCompleteButton.tsx, frontend/issue-cracker/src/components/layout/LogIn/index.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneAdd/MilestoneAddCompleteButton.tsx, frontend/issue-cracker/src/utils/const.ts
동작하지 않는 기능들을 없애면서, 사소하게 오동작하던 부분을 디버깅했습니다.
=> 동작하지 않는 기능들 주석처리

frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/CommentTextArea.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/IssueDetailComment.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/IssueDetailInputContent.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailHeader/IssueDetailHeaderButtonSection/index.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailHeader/IssueDetailHeaderInfoSection/IssueDetailButton.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneCell.tsx, frontend/issue-cracker/src/components/layout/Milestone/MilestoneTable/MilestoneTableHeader.tsx
비동기로 댓글이 추가되는 것을 구현하려고 했는데,
상태관리하는데 시간 많이 쏟기 귀찮아서,
일단은 무식하게 새로고침했습니다.
Closes #207
=> [FE] Comment 추가 API 연동

frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/CommentTextArea.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/IssueDetailBox/IssueDetailInput/IssueDetailInputContent.tsx, frontend/issue-cracker/src/components/layout/IssueDetail/index.tsx
아무리 그래도 자존심이 있지... 새로 고침은 너무한것 같아서,
비동기 동작하도록 구현했습니다.
Closes #207
=> [FE] 비동기로 댓글이 추가될수 있도록 함
